export default {
  TOGGLE_DROP_DOWN: "TOGGLE_DROP_DOWN",
  ADD_DATA_FROM_SERVER: 'ADD_DATA_FROM_SERVER',
  TOGGLE_CHECKBOX: 'TOGGLE_CHECKBOX',
  RESET: 'RESET',
  RESET_ALL: 'RESET_ALL',
  SUBMIT: 'SUBMIT',
};